# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Jinsoo Kim
title: Master Student
email: jinsoou0517@gmail.com
# email_title: Email (Email title override)
# phone: +82 10-5487-4484
# phone_title: Phone (Phone title override)
# website: https://sites.google.com/view/kvl
# website_title: KNU Vision & Learning Lab

# address:
#   street: IT1 309, 80 Daehak-ro
#   district: Buk-gu
#   city: Daegu
#   country: Korea
#   postal_code: 41566

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username: kimjin0517
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: 9bsecQIAAAAJ&hl=ko

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/Jinsu.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hello! I am a Master student at [KNU Multimodal Language & Cognition Lab](https://sites.google.com/view/mlc-lab), receiving guidance from Prof. <mark>Hoyoung Jung</mark>. My current research interests focus on sLLM, Chatbot for domain-specific and prompt engineering. Currently, I'm also interest in anormaly detections and medical data analysis.

  Besides research, I'm intereting in building anything.
    - knitting
    - yarn
    - building figure

content:
  - title: EDUCATION
    layout: list
    content:
      - layout: left
        title: Kyungpook National University
        # sub_title: Integrated Master's & Ph.D in Artificial Intelligence, KNU
        # caption: Dec. 2023 - Current, Prof. Heechul Jung
        description: | # this will include new lines to allow paragraphs
          - Integrated Master's in Artificial Intelligence, KNU
          - Dec. 2023 - Current, Prof. Hoyoung Jung
          - Mar. 2022 - Nov. 2023, Prof. Minho Lee
      - layout: left
        title: Kyungpook National University
        # sub_title: B.S. in Mathematics and Electronic Engineering (Double Major), KNU
        # caption: Mar. 2015 - Aug. 2020
        description: | # this will include new lines to allow paragraphs
          - B.S. in Electronic Engineering, KNU
          - Mar. 2016 - Feb. 2022, Prof. Aeryeong Seo

  - title: DOMESTIC CONFERENCES (IN KOREAN)
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Lee, J., Lee, M. (2023). Utilizing Artificial Intelligence for Battlefield Situation Recognition. Korea Institute of Military Science and Technology (KIMST).
  
  - title: PROJECTS # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Institute of Information & communications Technology Planning & Evaluation
        description: | # this will include new lines to allow paragraphs
          - Research on Innovative Technologies for Prediction Intelligence Based on Complex Information, Jan. 2021 - Dec. 2023.
          - Development of Intelligent SW Technology for Medical Data Analysis, Sep. 2020 - Feb. 2021.
         

      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: National Research Foundation of Korea 
        description: | # this will include new lines to allow paragraphs
          - Open Domain Knowledge Service Chatbot Development,  Mar. 2023 -
          - Decoding traditional records based on deep learning to build a metaverse virtual vow, Mar. 2022 -
          - Discovering problem-solving educational contents using AI platform, Jul. 2023 - Dec. 2023.
          - Establish AI solution consulting process for industry/academia/research activities, Sep. 2022 - Jul. 2023.
          - AI agents to create, utilize, and augment knowledge through conversations, Mar. 2022. - Sep 2023.
          - Recognizing and deciphering traditional written characters using deep learning technology, Jan. 2021 - Jul. 2021.
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Institute for Information & communication Technology Planning & evaluation
        description: | # this will include new lines to allow paragraphs
          - Research and development of intelligent interaction technology that understands user intent and context, Oct. 2020 - Dec. 2021.
  
  # - title: A Little More About Me
  #   layout: text
  #   content: | # this will include new lines to allow paragraphs
  #     This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

  #     Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
